//! Fibonacci assembly test for QJL bytecode
//! Based on the user-provided assembly:
//!
//! main:
//!     loadi r1, 25
//!     call fib, 1
//!     ret
//!
//! fib:
//!     ; if (n <= 1)
//!     loadi r2, 1
//!     cmp_le r3, r1, r2
//!     jmp_if_true r3, fib_base
//!
//!     ; ---- fib(n-1) ----
//!     loadi r2, 1
//!     sub r4, r1, r2
//!     mov r1, r4
//!     call fib, 1
//!     mov r5, r0
//!
//!     ; ---- fib(n-2) ----
//!     loadi r2, 2
//!     sub r4, r1, r2
//!     mov r1, r4
//!     call fib, 1
//!     mov r6, r0
//!
//!     ; return fib(n-1) + fib(n-2)
//!     add r0, r5, r6
//!     ret
//!
//! fib_base:
//!     mov r0, r1
//!     ret

use vm::asm::*;
use vm::emit::BytecodeBuilder;

fn main() {
    println!("=== Fibonacci Assembly Test ===\n");

    // Create bytecode for the Fibonacci program using BytecodeBuilder
    let mut builder = BytecodeBuilder::new();

    // main: loadi r1, 25
    builder.emit_load_i(1, 25); // load_i r1, 25

    // call fib (placeholder - we'll assume fib is at instruction 2)
    builder.emit_call(2, 1); // call instruction at offset 2, 1 arg

    // ret
    builder.emit_ret(); // ret

    // fib: loadi r2, 1
    builder.emit_load_i(2, 1); // load_i r2, 1

    // cmp_le: lte r1, r2 (result in accumulator)
    builder.emit_lte(1, 2); // lte r1, r2

    // jmp_if_true accumulator, fib_base (jump to instruction 12 if true)
    // Assuming fib_base is at instruction 12 (0x30 byte offset)
    // jmp_true checks accumulator, jumps if truthy
    builder.emit_jmp_true(255, 7); // jmp_true accumulator, +7 instructions

    // fib(n-1): loadi r2, 1
    builder.emit_load_i(2, 1); // load_i r2, 1

    // sub r4, r1, r2
    builder.emit_sub_i(4, 1, 1); // sub_i r4, r1, 1

    // mov r1, r4
    builder.emit_mov(1, 4); // mov r1, r4

    // call fib (recursive call back to instruction 3)
    builder.emit_call(3, 1); // call instruction 3, 1 arg

    // mov r5, r0
    builder.emit_mov(5, 255); // mov r5, accumulator

    // fib(n-2): loadi r2, 2
    builder.emit_load_i(2, 2); // load_i r2, 2

    // sub r4, r1, r2
    builder.emit_sub_i(4, 1, 2); // sub_i r4, r1, 2

    // mov r1, r4
    builder.emit_mov(1, 4); // mov r1, r4

    // call fib (recursive call back to instruction 3)
    builder.emit_call(3, 1); // call instruction 3, 1 arg

    // mov r6, r0
    builder.emit_mov(6, 255); // mov r6, accumulator

    // add r0, r5, r6
    builder.emit_add(5, 6); // add r5, r6 (result in accumulator)

    // ret
    builder.emit_ret(); // ret

    // fib_base: mov r0, r1
    builder.emit_mov(255, 1); // mov accumulator, r1

    // ret
    builder.emit_ret(); // ret

    let (bytecode, constants) = builder.build();

    println!("Generated bytecode ({} instructions):", bytecode.len());
    for (i, &instr) in bytecode.iter().enumerate() {
        println!("  {:04X}: {:08X}", i * 4, instr);
    }

    println!("\nDisassembled Assembly:");
    let asm = disassemble(&bytecode, &constants);
    for (i, line) in asm.iter().enumerate() {
        println!("  {:04X}: {}", i * 4, line);
    }

    println!("\n=== Program Structure ===");
    println!("Instructions 0-2: main function");
    println!("  - Load 25 into r1");
    println!("  - Call fib function (at instruction 3)");
    println!("  - Return");
    println!("\nInstructions 3-22: fib function (recursive)");
    println!("  - Base case check (n <= 1)");
    println!("  - If true, jump to fib_base (instruction 23)");
    println!("  - Otherwise compute fib(n-1)");
    println!("  - Compute fib(n-2)");
    println!("  - Add results and return");
    println!("\nInstructions 23-24: fib_base case");
    println!("  - Return n (when n <= 1)");

    println!("\n=== Note ===");
    println!("This is a demonstration of assembly code generation.");
    println!("The actual Fibonacci computation would require a working VM");
    println!("to execute the bytecode. The assembly generation itself works correctly.");
}
