use vm::asm::disassemble_clean;
use vm::mandelbrot::{
    build_escape_iterations_program, reference_escape_iterations, run_escape_iterations,
};

fn main() {
    println!("=== Mandelbrot Assembly Test ===\n");

    let sample_cx = 1.0;
    let sample_cy = 0.0;
    let sample_max_iter = 8;
    let (bytecode, constants) =
        build_escape_iterations_program(sample_cx, sample_cy, sample_max_iter);

    println!("Sample point: c = ({sample_cx}, {sample_cy}), max_iter = {sample_max_iter}");
    println!(
        "Expected escape iterations: {}\n",
        reference_escape_iterations(sample_cx, sample_cy, sample_max_iter)
    );

    println!("Generated bytecode ({} instructions):", bytecode.len());
    for (i, line) in disassemble_clean(&bytecode, &constants).iter().enumerate() {
        println!("  {:3}: {}", i, line);
    }

    println!("\n=== Small Checks ===");
    let cases = [
        ("origin", 0.0, 0.0, 8u16),
        ("escape_fast", 1.0, 0.0, 8u16),
        ("inside_period2", -1.0, 0.0, 8u16),
        ("edge_sample", -0.75, 0.1, 16u16),
    ];

    for (name, cx, cy, max_iter) in cases {
        let expected = reference_escape_iterations(cx, cy, max_iter);
        let actual = run_escape_iterations(cx, cy, max_iter);
        println!(
            "{name}: c = ({cx}, {cy}), max_iter = {max_iter} -> {actual} (expected {expected})"
        );
        assert_eq!(actual, expected, "{name} mismatch");
    }

    println!("\nAll Mandelbrot small checks matched the Rust reference.");
}
