//! Bytecode builder for generating QJL bytecode
//!
//! Provides a clean, type-safe API for generating bytecode instructions.

use crate::js_value::{JSValue, make_number};
use crate::vm::Opcode;
use crate::vm::optimization::optimize_bytecode;

/// Builder for generating bytecode instructions
#[derive(Debug, Default)]
pub struct BytecodeBuilder {
    /// Generated bytecode instructions
    code: Vec<u32>,
    /// Constant pool for the bytecode
    constants: Vec<crate::js_value::JSValue>,
}

impl BytecodeBuilder {
    /// Create a new empty bytecode builder
    pub fn new() -> Self {
        Self {
            code: Vec::new(),
            constants: Vec::new(),
        }
    }

    /// Create a new bytecode builder with initial capacity
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            code: Vec::with_capacity(capacity),
            constants: Vec::new(),
        }
    }

    /// Add a constant to the constant pool and return its index
    pub fn add_constant(&mut self, value: crate::js_value::JSValue) -> u16 {
        let index = self.constants.len();
        self.constants.push(value);
        index as u16
    }

    /// Add a switch jump table to the constant pool and return its start index.
    ///
    /// Layout:
    /// `[case_count, default_offset, case_0_value, case_0_offset, ...]`
    ///
    /// Offsets are relative to the instruction immediately after `switch`.
    pub fn add_switch_table(&mut self, default_offset: i16, cases: &[(JSValue, i16)]) -> u8 {
        let index =
            u8::try_from(self.constants.len()).expect("switch table start index must fit in u8");
        self.constants.push(make_number(cases.len() as f64));
        self.constants.push(make_number(default_offset as f64));
        for &(value, offset) in cases {
            self.constants.push(value);
            self.constants.push(make_number(offset as f64));
        }
        index
    }

    /// Get the current instruction count
    pub fn len(&self) -> usize {
        self.code.len()
    }

    /// Check if the builder is empty
    pub fn is_empty(&self) -> bool {
        self.code.is_empty()
    }

    /// Get the generated bytecode
    pub fn bytecode(&self) -> &[u32] {
        &self.code
    }

    /// Get the constant pool
    pub fn constants(&self) -> &[crate::js_value::JSValue] {
        &self.constants
    }

    /// Build and return the bytecode and constants
    pub fn build(self) -> (Vec<u32>, Vec<crate::js_value::JSValue>) {
        (self.code, self.constants)
    }

    /// Optimize the currently generated bytecode in place.
    pub fn optimize(&mut self) {
        let code = std::mem::take(&mut self.code);
        let constants = std::mem::take(&mut self.constants);
        let (optimized_code, optimized_constants) = optimize_bytecode(code, constants);
        self.code = optimized_code;
        self.constants = optimized_constants;
    }

    /// Optimize and build the bytecode and constants.
    pub fn build_optimized(mut self) -> (Vec<u32>, Vec<crate::js_value::JSValue>) {
        self.optimize();
        self.build()
    }

    /// Emit a raw instruction
    fn emit_raw(&mut self, opcode: u8, a: u8, b: u8, c: u8) {
        let instr = ((c as u32) << 24) | ((b as u32) << 16) | ((a as u32) << 8) | opcode as u32;
        self.code.push(instr);
    }

    /// Emit an ABx format instruction
    fn emit_abx(&mut self, opcode: u8, a: u8, bx: u16) {
        let instr = ((bx as u32) << 16) | ((a as u32) << 8) | opcode as u32;
        self.code.push(instr);
    }

    /// Emit an AsBx format instruction
    fn emit_asbx(&mut self, opcode: u8, a: u8, sbx: i16) {
        let instr = (((sbx as u16) as u32) << 16) | ((a as u32) << 8) | opcode as u32;
        self.code.push(instr);
    }

    // ===== Core Instructions =====

    /// mov dst, src
    pub fn emit_mov(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::Mov.as_u8(), dst, src, 0);
    }

    /// load_k dst, const[index]
    pub fn emit_load_k(&mut self, dst: u8, const_index: u16) {
        self.emit_abx(Opcode::LoadK.as_u8(), dst, const_index);
    }

    /// add lhs, rhs (result in accumulator)
    pub fn emit_add(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Add.as_u8(), 0, lhs, rhs);
    }

    /// get_prop_ic dst, obj, key
    pub fn emit_get_prop_ic(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetPropIc.as_u8(), dst, obj, key);
    }

    /// call callee, arg_count
    /// Arguments must be placed in consecutive registers starting at `callee + 1`.
    pub fn emit_call(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::Call.as_u8(), callee, arg_count, 0);
    }

    /// call1_subi callee, src, imm
    /// Computes `src - imm` and calls `callee` with that single argument.
    pub fn emit_call1_sub_i(&mut self, callee: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::Call1SubI.as_u8(), callee, src, imm as u8);
    }

    /// jmp -> offset
    pub fn emit_jmp(&mut self, offset: i16) {
        self.emit_asbx(Opcode::Jmp.as_u8(), 0, offset);
    }

    /// load_i dst, value
    pub fn emit_load_i(&mut self, dst: u8, value: i16) {
        self.emit_asbx(Opcode::LoadI.as_u8(), dst, value);
    }

    /// jmp_true cond, offset
    pub fn emit_jmp_true(&mut self, cond: u8, offset: i16) {
        self.emit_asbx(Opcode::JmpTrue.as_u8(), cond, offset);
    }

    /// jmp_false cond, offset
    pub fn emit_jmp_false(&mut self, cond: u8, offset: i16) {
        self.emit_asbx(Opcode::JmpFalse.as_u8(), cond, offset);
    }

    /// jmp_lte_false lhs, rhs, offset
    /// Jumps when `lhs <= rhs` is false. Offset must fit in i8.
    pub fn emit_jmp_lte_false(&mut self, lhs: u8, rhs: u8, offset: i8) {
        self.emit_raw(Opcode::JmpLteFalse.as_u8(), lhs, rhs, offset as u8);
    }

    /// set_prop_ic obj, key, value
    pub fn emit_set_prop_ic(&mut self, value: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::SetPropIc.as_u8(), value, obj, key);
    }

    /// add_acc_imm8 value
    pub fn emit_add_acc_imm8(&mut self, value: i8) {
        self.emit_raw(Opcode::AddAccImm8.as_u8(), 0, value as u8, 0);
    }

    /// inc_acc
    pub fn emit_inc_acc(&mut self) {
        self.emit_raw(Opcode::IncAcc.as_u8(), 0, 0, 0);
    }

    /// load_this
    pub fn emit_load_this(&mut self) {
        self.emit_raw(Opcode::LoadThis.as_u8(), 0, 0, 0);
    }

    /// load_0
    pub fn emit_load_0(&mut self) {
        self.emit_raw(Opcode::Load0.as_u8(), 0, 0, 0);
    }

    /// load_1
    pub fn emit_load_1(&mut self) {
        self.emit_raw(Opcode::Load1.as_u8(), 0, 0, 0);
    }

    /// eq lhs, rhs (result in accumulator)
    pub fn emit_eq(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Eq.as_u8(), 0, lhs, rhs);
    }

    /// lt lhs, rhs (result in accumulator)
    pub fn emit_lt(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Lt.as_u8(), 0, lhs, rhs);
    }

    /// lte lhs, rhs (result in accumulator)
    pub fn emit_lte(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Lte.as_u8(), 0, lhs, rhs);
    }

    /// add_acc src
    pub fn emit_add_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::AddAcc.as_u8(), 0, src, 0);
    }

    /// sub_acc src
    pub fn emit_sub_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::SubAcc.as_u8(), 0, src, 0);
    }

    /// mul_acc src
    pub fn emit_mul_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::MulAcc.as_u8(), 0, src, 0);
    }

    /// div_acc src
    pub fn emit_div_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::DivAcc.as_u8(), 0, src, 0);
    }

    /// load_null
    pub fn emit_load_null(&mut self) {
        self.emit_raw(Opcode::LoadNull.as_u8(), 0, 0, 0);
    }

    /// load_true -> dst
    pub fn emit_load_true(&mut self, dst: u8) {
        self.emit_raw(Opcode::LoadTrue.as_u8(), dst, 0, 0);
    }

    /// load_false -> dst
    pub fn emit_load_false(&mut self, dst: u8) {
        self.emit_raw(Opcode::LoadFalse.as_u8(), dst, 0, 0);
    }

    /// load_global_ic dst, global_id
    pub fn emit_load_global_ic(&mut self, dst: u8, global_id: u16) {
        self.emit_abx(Opcode::LoadGlobalIc.as_u8(), dst, global_id);
    }

    /// set_global_ic src, global_id
    pub fn emit_set_global_ic(&mut self, src: u8, global_id: u16) {
        self.emit_abx(Opcode::SetGlobalIc.as_u8(), src, global_id);
    }

    /// typeof dst, src
    pub fn emit_typeof(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::Typeof.as_u8(), dst, src, 0);
    }

    /// to_num dst, src
    pub fn emit_to_num(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::ToNum.as_u8(), dst, src, 0);
    }

    /// to_str dst, src
    pub fn emit_to_str(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::ToStr.as_u8(), dst, src, 0);
    }

    /// is_undef dst, src
    pub fn emit_is_undef(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::IsUndef.as_u8(), dst, src, 0);
    }

    /// is_null dst, src
    pub fn emit_is_null(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::IsNull.as_u8(), dst, src, 0);
    }

    /// sub_acc_imm8 value
    pub fn emit_sub_acc_imm8(&mut self, value: i8) {
        self.emit_raw(Opcode::SubAccImm8.as_u8(), 0, value as u8, 0);
    }

    /// mul_acc_imm8 value
    pub fn emit_mul_acc_imm8(&mut self, value: i8) {
        self.emit_raw(Opcode::MulAccImm8.as_u8(), 0, value as u8, 0);
    }

    /// div_acc_imm8 value
    pub fn emit_div_acc_imm8(&mut self, value: i8) {
        self.emit_raw(Opcode::DivAccImm8.as_u8(), 0, value as u8, 0);
    }

    /// add_str_acc src
    pub fn emit_add_str_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::AddStrAcc.as_u8(), 0, src, 0);
    }

    /// add_i dst, src, imm
    pub fn emit_add_i(&mut self, dst: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::AddI.as_u8(), dst, src, imm as u8);
    }

    /// sub_i dst, src, imm
    pub fn emit_sub_i(&mut self, dst: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::SubI.as_u8(), dst, src, imm as u8);
    }

    /// mul_i dst, src, imm
    pub fn emit_mul_i(&mut self, dst: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::MulI.as_u8(), dst, src, imm as u8);
    }

    /// div_i dst, src, imm
    pub fn emit_div_i(&mut self, dst: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::DivI.as_u8(), dst, src, imm as u8);
    }

    /// mod_i dst, src, imm
    pub fn emit_mod_i(&mut self, dst: u8, src: u8, imm: i8) {
        self.emit_raw(Opcode::ModI.as_u8(), dst, src, imm as u8);
    }

    /// neg src (result in accumulator)
    pub fn emit_neg(&mut self, src: u8) {
        self.emit_raw(Opcode::Neg.as_u8(), 0, src, 0);
    }

    /// inc src (result in accumulator)
    pub fn emit_inc(&mut self, src: u8) {
        self.emit_raw(Opcode::Inc.as_u8(), 0, src, 0);
    }

    /// dec src (result in accumulator)
    pub fn emit_dec(&mut self, src: u8) {
        self.emit_raw(Opcode::Dec.as_u8(), 0, src, 0);
    }

    /// add_str lhs, rhs (result in accumulator)
    pub fn emit_add_str(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AddStr.as_u8(), 0, lhs, rhs);
    }

    /// to_primitive src (result in accumulator)
    pub fn emit_to_primitive(&mut self, src: u8) {
        self.emit_raw(Opcode::ToPrimitive.as_u8(), 0, src, 0);
    }

    /// get_prop_acc obj, key (result in accumulator)
    pub fn emit_get_prop_acc(&mut self, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetPropAcc.as_u8(), 0, obj, key);
    }

    /// set_prop_acc obj, key (value from accumulator)
    pub fn emit_set_prop_acc(&mut self, obj: u8, key: u8) {
        self.emit_raw(Opcode::SetPropAcc.as_u8(), 0, obj, key);
    }

    /// get_idx_fast dst, obj, index
    pub fn emit_get_idx_fast(&mut self, dst: u8, obj: u8, index: u8) {
        self.emit_raw(Opcode::GetIdxFast.as_u8(), dst, obj, index);
    }

    /// set_idx_fast obj, index, value
    pub fn emit_set_idx_fast(&mut self, value: u8, obj: u8, index: u8) {
        self.emit_raw(Opcode::SetIdxFast.as_u8(), value, obj, index);
    }

    /// load_arg dst, arg_index
    pub fn emit_load_arg(&mut self, dst: u8, arg_index: u8) {
        self.emit_raw(Opcode::LoadArg.as_u8(), dst, arg_index, 0);
    }

    /// load_acc src
    pub fn emit_load_acc(&mut self, src: u8) {
        self.emit_raw(Opcode::LoadAcc.as_u8(), src, 0, 0);
    }

    /// strict_eq lhs, rhs (result in accumulator)
    pub fn emit_strict_eq(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::StrictEq.as_u8(), 0, lhs, rhs);
    }

    /// strict_neq lhs, rhs (result in accumulator)
    pub fn emit_strict_neq(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::StrictNeq.as_u8(), 0, lhs, rhs);
    }

    /// bit_and lhs, rhs (result in accumulator)
    pub fn emit_bit_and(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::BitAnd.as_u8(), 0, lhs, rhs);
    }

    /// bit_or lhs, rhs (result in accumulator)
    pub fn emit_bit_or(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::BitOr.as_u8(), 0, lhs, rhs);
    }

    /// bit_xor lhs, rhs (result in accumulator)
    pub fn emit_bit_xor(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::BitXor.as_u8(), 0, lhs, rhs);
    }

    /// bit_not src (result in accumulator)
    pub fn emit_bit_not(&mut self, src: u8) {
        self.emit_raw(Opcode::BitNot.as_u8(), 0, src, 0);
    }

    /// shl lhs, rhs (result in accumulator)
    pub fn emit_shl(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Shl.as_u8(), 0, lhs, rhs);
    }

    /// shr lhs, rhs (result in accumulator)
    pub fn emit_shr(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Shr.as_u8(), 0, lhs, rhs);
    }

    /// ushr lhs, rhs (result in accumulator)
    pub fn emit_ushr(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Ushr.as_u8(), 0, lhs, rhs);
    }

    /// pow lhs, rhs (result in accumulator)
    pub fn emit_pow(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Pow.as_u8(), 0, lhs, rhs);
    }

    /// logical_and lhs, rhs (result in accumulator)
    pub fn emit_logical_and(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::LogicalAnd.as_u8(), 0, lhs, rhs);
    }

    /// logical_or lhs, rhs (result in accumulator)
    pub fn emit_logical_or(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::LogicalOr.as_u8(), 0, lhs, rhs);
    }

    /// nullish_coalesce lhs, rhs (result in accumulator)
    pub fn emit_nullish_coalesce(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::NullishCoalesce.as_u8(), 0, lhs, rhs);
    }

    /// in lhs, rhs (result in accumulator)
    pub fn emit_in(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::In.as_u8(), 0, lhs, rhs);
    }

    /// instanceof lhs, rhs (result in accumulator)
    pub fn emit_instanceof(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::Instanceof.as_u8(), 0, lhs, rhs);
    }

    /// get_length_ic dst, obj, cache_slot
    pub fn emit_get_length_ic(&mut self, dst: u8, obj: u8, cache_slot: u8) {
        self.emit_raw(Opcode::GetLengthIc.as_u8(), dst, obj, cache_slot);
    }

    /// array_push_acc array
    pub fn emit_array_push_acc(&mut self, array: u8) {
        self.emit_raw(Opcode::ArrayPushAcc.as_u8(), array, 0, 0);
    }

    /// new_obj dst
    pub fn emit_new_obj(&mut self, dst: u8) {
        self.emit_raw(Opcode::NewObj.as_u8(), dst, 0, 0);
    }

    /// new_arr dst, size_hint
    pub fn emit_new_arr(&mut self, dst: u8, size_hint: u8) {
        self.emit_raw(Opcode::NewArr.as_u8(), dst, size_hint, 0);
    }

    /// new_func dst, const_index
    pub fn emit_new_func(&mut self, dst: u8, const_index: u16) {
        self.emit_abx(Opcode::NewFunc.as_u8(), dst, const_index);
    }

    /// new_class dst, base
    pub fn emit_new_class(&mut self, dst: u8, base: u8) {
        self.emit_raw(Opcode::NewClass.as_u8(), dst, base, 0);
    }

    /// get_prop dst, obj, key
    pub fn emit_get_prop(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetProp.as_u8(), dst, obj, key);
    }

    /// set_prop obj, key, value
    pub fn emit_set_prop(&mut self, value: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::SetProp.as_u8(), value, obj, key);
    }

    /// get_idx_ic dst, obj, cache_slot
    pub fn emit_get_idx_ic(&mut self, dst: u8, obj: u8, cache_slot: u8) {
        self.emit_raw(Opcode::GetIdxIc.as_u8(), dst, obj, cache_slot);
    }

    /// set_idx_ic obj, cache_slot, value
    pub fn emit_set_idx_ic(&mut self, value: u8, obj: u8, cache_slot: u8) {
        self.emit_raw(Opcode::SetIdxIc.as_u8(), value, obj, cache_slot);
    }

    /// get_global dst, global_id
    pub fn emit_get_global(&mut self, dst: u8, global_id: u16) {
        self.emit_abx(Opcode::GetGlobal.as_u8(), dst, global_id);
    }

    /// set_global src, global_id
    pub fn emit_set_global(&mut self, src: u8, global_id: u16) {
        self.emit_abx(Opcode::SetGlobal.as_u8(), src, global_id);
    }

    /// get_upval dst, slot
    pub fn emit_get_upval(&mut self, dst: u8, slot: u8) {
        self.emit_raw(Opcode::GetUpval.as_u8(), dst, slot, 0);
    }

    /// set_upval src, slot
    pub fn emit_set_upval(&mut self, src: u8, slot: u8) {
        self.emit_raw(Opcode::SetUpval.as_u8(), src, slot, 0);
    }

    /// get_scope dst, depth
    pub fn emit_get_scope(&mut self, dst: u8, depth: u8) {
        self.emit_raw(Opcode::GetScope.as_u8(), dst, depth, 0);
    }

    /// set_scope src, depth
    pub fn emit_set_scope(&mut self, src: u8, depth: u8) {
        self.emit_raw(Opcode::SetScope.as_u8(), src, depth, 0);
    }

    /// resolve_scope dst, name_id
    pub fn emit_resolve_scope(&mut self, dst: u8, name_id: u16) {
        self.emit_abx(Opcode::ResolveScope.as_u8(), dst, name_id);
    }

    /// get_super dst, obj, key
    pub fn emit_get_super(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetSuper.as_u8(), dst, obj, key);
    }

    /// set_super obj, key, value
    pub fn emit_set_super(&mut self, value: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::SetSuper.as_u8(), value, obj, key);
    }

    /// delete_prop dst, obj, key
    pub fn emit_delete_prop(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::DeleteProp.as_u8(), dst, obj, key);
    }

    /// has_prop dst, obj, key
    pub fn emit_has_prop(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::HasProp.as_u8(), dst, obj, key);
    }

    /// keys dst, obj
    pub fn emit_keys(&mut self, dst: u8, obj: u8) {
        self.emit_raw(Opcode::Keys.as_u8(), dst, obj, 0);
    }

    /// for_in dst, obj
    pub fn emit_for_in(&mut self, dst: u8, obj: u8) {
        self.emit_raw(Opcode::ForIn.as_u8(), dst, obj, 0);
    }

    /// iterator_next dst, iterator
    pub fn emit_iterator_next(&mut self, dst: u8, iterator: u8) {
        self.emit_raw(Opcode::IteratorNext.as_u8(), dst, iterator, 0);
    }

    /// spread dst, src
    pub fn emit_spread(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::Spread.as_u8(), dst, src, 0);
    }

    /// destructure dst, src
    pub fn emit_destructure(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::Destructure.as_u8(), dst, src, 0);
    }

    /// create_env dst
    pub fn emit_create_env(&mut self, dst: u8) {
        self.emit_raw(Opcode::CreateEnv.as_u8(), dst, 0, 0);
    }

    /// load_name dst, name_id
    pub fn emit_load_name(&mut self, dst: u8, name_id: u16) {
        self.emit_abx(Opcode::LoadName.as_u8(), dst, name_id);
    }

    /// store_name src, name_id
    pub fn emit_store_name(&mut self, src: u8, name_id: u16) {
        self.emit_abx(Opcode::StoreName.as_u8(), src, name_id);
    }

    /// load_closure dst, slot
    pub fn emit_load_closure(&mut self, dst: u8, slot: u8) {
        self.emit_raw(Opcode::LoadClosure.as_u8(), dst, slot, 0);
    }

    /// new_this dst
    pub fn emit_new_this(&mut self, dst: u8) {
        self.emit_raw(Opcode::NewThis.as_u8(), dst, 0, 0);
    }

    /// typeof_name dst, name_id
    pub fn emit_typeof_name(&mut self, dst: u8, name_id: u16) {
        self.emit_abx(Opcode::TypeofName.as_u8(), dst, name_id);
    }

    /// jmp_eq a, b, offset
    pub fn emit_jmp_eq(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::JmpEq.as_u8(), a, b, offset as u8);
    }

    /// jmp_neq a, b, offset
    pub fn emit_jmp_neq(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::JmpNeq.as_u8(), a, b, offset as u8);
    }

    /// jmp_lt a, b, offset
    pub fn emit_jmp_lt(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::JmpLt.as_u8(), a, b, offset as u8);
    }

    /// jmp_lte a, b, offset
    pub fn emit_jmp_lte(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::JmpLte.as_u8(), a, b, offset as u8);
    }

    /// loop_inc_jmp counter, limit, offset
    pub fn emit_loop_inc_jmp(&mut self, counter: u8, _limit: u8, offset: i16) {
        self.emit_asbx(Opcode::LoopIncJmp.as_u8(), counter, offset);
        // Note: limit is stored in accumulator
    }

    /// switch value, table_index
    pub fn emit_switch(&mut self, value: u8, table_index: u8) {
        self.emit_raw(Opcode::Switch.as_u8(), value, table_index, 0);
    }

    /// loop_hint
    pub fn emit_loop_hint(&mut self) {
        self.emit_raw(Opcode::LoopHint.as_u8(), 0, 0, 0);
    }

    /// ret
    pub fn emit_ret(&mut self) {
        self.emit_raw(Opcode::Ret.as_u8(), 0, 0, 0);
    }

    /// ret_reg src
    pub fn emit_ret_reg(&mut self, src: u8) {
        self.emit_raw(Opcode::RetReg.as_u8(), src, 0, 0);
    }

    /// ret_u
    pub fn emit_ret_u(&mut self) {
        self.emit_raw(Opcode::RetU.as_u8(), 0, 0, 0);
    }

    /// tail_call callee, arg_count
    pub fn emit_tail_call(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::TailCall.as_u8(), callee, arg_count, 0);
    }

    /// construct callee, arg_count
    pub fn emit_construct(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::Construct.as_u8(), callee, arg_count, 0);
    }

    /// call_var callee, array_reg
    pub fn emit_call_var(&mut self, callee: u8, array_reg: u8) {
        self.emit_raw(Opcode::CallVar.as_u8(), callee, array_reg, 0);
    }

    /// enter frame_size
    pub fn emit_enter(&mut self, frame_size: u16) {
        self.emit_abx(Opcode::Enter.as_u8(), 0, frame_size);
    }

    /// leave
    pub fn emit_leave(&mut self) {
        self.emit_raw(Opcode::Leave.as_u8(), 0, 0, 0);
    }

    /// yield src
    pub fn emit_yield(&mut self, src: u8) {
        self.emit_raw(Opcode::Yield.as_u8(), src, 0, 0);
    }

    /// await src
    pub fn emit_await(&mut self, src: u8) {
        self.emit_raw(Opcode::Await.as_u8(), src, 0, 0);
    }

    /// throw src
    pub fn emit_throw(&mut self, src: u8) {
        self.emit_raw(Opcode::Throw.as_u8(), src, 0, 0);
    }

    /// try offset
    pub fn emit_try(&mut self, offset: i16) {
        self.emit_asbx(Opcode::Try.as_u8(), 0, offset);
    }

    /// end_try
    pub fn emit_end_try(&mut self) {
        self.emit_raw(Opcode::EndTry.as_u8(), 0, 0, 0);
    }

    /// catch dst
    pub fn emit_catch(&mut self, dst: u8) {
        self.emit_raw(Opcode::Catch.as_u8(), dst, 0, 0);
    }

    /// finally
    pub fn emit_finally(&mut self) {
        self.emit_raw(Opcode::Finally.as_u8(), 0, 0, 0);
    }

    /// call_ic callee, arg_count
    pub fn emit_call_ic(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::CallIc.as_u8(), callee, arg_count, 0);
    }

    /// call_ic_var callee, array_reg
    pub fn emit_call_ic_var(&mut self, callee: u8, array_reg: u8) {
        self.emit_raw(Opcode::CallIcVar.as_u8(), callee, array_reg, 0);
    }

    /// profile_type type_id
    pub fn emit_profile_type(&mut self, type_id: u8) {
        self.emit_raw(Opcode::ProfileType.as_u8(), type_id, 0, 0);
    }

    /// profile_call call_site
    pub fn emit_profile_call(&mut self, call_site: u8) {
        self.emit_raw(Opcode::ProfileCall.as_u8(), call_site, 0, 0);
    }

    /// profile_ret
    pub fn emit_profile_ret(&mut self) {
        self.emit_raw(Opcode::ProfileRet.as_u8(), 0, 0, 0);
    }

    /// check_type type_id
    pub fn emit_check_type(&mut self, type_id: u8) {
        self.emit_raw(Opcode::CheckType.as_u8(), type_id, 0, 0);
    }

    /// check_struct struct_id
    pub fn emit_check_struct(&mut self, struct_id: u8) {
        self.emit_raw(Opcode::CheckStruct.as_u8(), struct_id, 0, 0);
    }

    /// check_ic cache_slot
    pub fn emit_check_ic(&mut self, cache_slot: u8) {
        self.emit_raw(Opcode::CheckIc.as_u8(), cache_slot, 0, 0);
    }

    /// ic_init cache_slot
    pub fn emit_ic_init(&mut self, cache_slot: u8) {
        self.emit_raw(Opcode::IcInit.as_u8(), cache_slot, 0, 0);
    }

    /// ic_update cache_slot
    pub fn emit_ic_update(&mut self, cache_slot: u8) {
        self.emit_raw(Opcode::IcUpdate.as_u8(), cache_slot, 0, 0);
    }

    /// ic_miss
    pub fn emit_ic_miss(&mut self) {
        self.emit_raw(Opcode::IcMiss.as_u8(), 0, 0, 0);
    }

    /// osr_entry
    pub fn emit_osr_entry(&mut self) {
        self.emit_raw(Opcode::OsrEntry.as_u8(), 0, 0, 0);
    }

    /// profile_hot_loop
    pub fn emit_profile_hot_loop(&mut self) {
        self.emit_raw(Opcode::ProfileHotLoop.as_u8(), 0, 0, 0);
    }

    /// osr_exit
    pub fn emit_osr_exit(&mut self) {
        self.emit_raw(Opcode::OsrExit.as_u8(), 0, 0, 0);
    }

    /// jit_hint
    pub fn emit_jit_hint(&mut self) {
        self.emit_raw(Opcode::JitHint.as_u8(), 0, 0, 0);
    }

    /// safety_check
    pub fn emit_safety_check(&mut self) {
        self.emit_raw(Opcode::SafetyCheck.as_u8(), 0, 0, 0);
    }

    /// get_prop_ic_call dst, obj, key
    pub fn emit_get_prop_ic_call(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetPropIcCall.as_u8(), dst, obj, key);
    }

    /// inc_jmp_false_loop counter, offset
    pub fn emit_inc_jmp_false_loop(&mut self, counter: u8, offset: i16) {
        self.emit_asbx(Opcode::IncJmpFalseLoop.as_u8(), counter, offset);
    }

    /// load_k_add_acc const_index
    pub fn emit_load_k_add_acc(&mut self, const_index: u16) {
        self.emit_abx(Opcode::LoadKAddAcc.as_u8(), 0, const_index);
    }

    /// add_mov dst, lhs, rhs
    pub fn emit_add_mov(&mut self, dst: u8, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AddMov.as_u8(), dst, lhs, rhs);
    }

    /// eq_jmp_true a, b, offset
    pub fn emit_eq_jmp_true(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::EqJmpTrue.as_u8(), a, b, offset as u8);
    }

    /// get_prop_acc_call obj, key
    pub fn emit_get_prop_acc_call(&mut self, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetPropAccCall.as_u8(), 0, obj, key);
    }

    /// load_k_mul_acc const_index
    pub fn emit_load_k_mul_acc(&mut self, const_index: u16) {
        self.emit_abx(Opcode::LoadKMulAcc.as_u8(), 0, const_index);
    }

    /// lt_jmp a, b, offset
    pub fn emit_lt_jmp(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::LtJmp.as_u8(), a, b, offset as u8);
    }

    /// get_prop_ic_mov dst, obj, key
    pub fn emit_get_prop_ic_mov(&mut self, dst: u8, obj: u8, key: u8) {
        self.emit_raw(Opcode::GetPropIcMov.as_u8(), dst, obj, key);
    }

    /// get_prop_add_imm_set_prop_ic obj, key, imm
    pub fn emit_get_prop_add_imm_set_prop_ic(&mut self, obj: u8, key: u8, imm: i8) {
        self.emit_raw(Opcode::GetPropAddImmSetPropIc.as_u8(), imm as u8, obj, key);
    }

    /// add_acc_imm8_mov dst, imm
    pub fn emit_add_acc_imm8_mov(&mut self, dst: u8, imm: i8) {
        self.emit_raw(Opcode::AddAccImm8Mov.as_u8(), dst, imm as u8, 0);
    }

    /// call_ic_super callee, arg_count
    pub fn emit_call_ic_super(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::CallIcSuper.as_u8(), callee, arg_count, 0);
    }

    /// load_this_call
    pub fn emit_load_this_call(&mut self) {
        self.emit_raw(Opcode::LoadThisCall.as_u8(), 0, 0, 0);
    }

    /// eq_jmp_false a, b, offset
    pub fn emit_eq_jmp_false(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::EqJmpFalse.as_u8(), a, b, offset as u8);
    }

    /// load_k_sub_acc const_index
    pub fn emit_load_k_sub_acc(&mut self, const_index: u16) {
        self.emit_abx(Opcode::LoadKSubAcc.as_u8(), 0, const_index);
    }

    /// get_length_ic_call obj, cache_slot
    pub fn emit_get_length_ic_call(&mut self, obj: u8, cache_slot: u8) {
        self.emit_raw(Opcode::GetLengthIcCall.as_u8(), 0, obj, cache_slot);
    }

    /// add_str_acc_mov dst, src
    pub fn emit_add_str_acc_mov(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::AddStrAccMov.as_u8(), dst, src, 0);
    }

    /// inc_acc_jmp offset
    pub fn emit_inc_acc_jmp(&mut self, offset: i16) {
        self.emit_asbx(Opcode::IncAccJmp.as_u8(), 0, offset);
    }

    /// get_prop_chain_acc base_reg, key
    pub fn emit_get_prop_chain_acc(&mut self, base_reg: u8, key: u8) {
        self.emit_raw(Opcode::GetPropChainAcc.as_u8(), 0, base_reg, key);
    }

    /// test_jmp_true cond, offset
    pub fn emit_test_jmp_true(&mut self, cond: u8, offset: i16) {
        self.emit_asbx(Opcode::TestJmpTrue.as_u8(), cond, offset);
    }

    /// load_arg_call dst, arg_index
    pub fn emit_load_arg_call(&mut self, dst: u8, arg_index: u8) {
        self.emit_raw(Opcode::LoadArgCall.as_u8(), dst, arg_index, 0);
    }

    /// mul_acc_mov dst, src
    pub fn emit_mul_acc_mov(&mut self, dst: u8, src: u8) {
        self.emit_raw(Opcode::MulAccMov.as_u8(), dst, src, 0);
    }

    /// lte_jmp_loop a, b, offset
    pub fn emit_lte_jmp_loop(&mut self, a: u8, b: u8, offset: i8) {
        self.emit_raw(Opcode::LteJmpLoop.as_u8(), a, b, offset as u8);
    }

    /// new_obj_init_prop dst, value, key
    pub fn emit_new_obj_init_prop(&mut self, dst: u8, value: u8, key: u8) {
        self.emit_raw(Opcode::NewObjInitProp.as_u8(), dst, value, key);
    }

    /// profile_hot_call callee, arg_count
    pub fn emit_profile_hot_call(&mut self, callee: u8, arg_count: u8) {
        self.emit_raw(Opcode::ProfileHotCall.as_u8(), 0, callee, arg_count);
    }

    // ===== Assertion Instructions =====

    /// assert_value src - check if value is truthy
    pub fn emit_assert_value(&mut self, src: u8) {
        self.emit_raw(Opcode::AssertValue.as_u8(), src, 0, 0);
    }

    /// assert_ok src - check if value is not an error/exception
    pub fn emit_assert_ok(&mut self, src: u8) {
        self.emit_raw(Opcode::AssertOk.as_u8(), src, 0, 0);
    }

    /// assert_equal lhs, rhs - check if values are equal (abstract equality)
    pub fn emit_assert_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_not_equal lhs, rhs - check if values are not equal
    pub fn emit_assert_not_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertNotEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_deep_equal lhs, rhs - check deep equality
    pub fn emit_assert_deep_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertDeepEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_not_deep_equal lhs, rhs
    pub fn emit_assert_not_deep_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertNotDeepEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_strict_equal lhs, rhs
    pub fn emit_assert_strict_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertStrictEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_not_strict_equal lhs, rhs
    pub fn emit_assert_not_strict_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertNotStrictEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_deep_strict_equal lhs, rhs
    pub fn emit_assert_deep_strict_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertDeepStrictEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_not_deep_strict_equal lhs, rhs
    pub fn emit_assert_not_deep_strict_equal(&mut self, lhs: u8, rhs: u8) {
        self.emit_raw(Opcode::AssertNotDeepStrictEqual.as_u8(), 0, lhs, rhs);
    }

    /// assert_throws fn - check if function throws
    pub fn emit_assert_throws(&mut self, fn_reg: u8) {
        self.emit_raw(Opcode::AssertThrows.as_u8(), fn_reg, 0, 0);
    }

    /// assert_does_not_throw fn - check if function doesn't throw
    pub fn emit_assert_does_not_throw(&mut self, fn_reg: u8) {
        self.emit_raw(Opcode::AssertDoesNotThrow.as_u8(), fn_reg, 0, 0);
    }

    /// assert_rejects promise - check if promise rejects
    pub fn emit_assert_rejects(&mut self, promise_reg: u8) {
        self.emit_raw(Opcode::AssertRejects.as_u8(), promise_reg, 0, 0);
    }

    /// assert_does_not_reject promise - check if promise doesn't reject
    pub fn emit_assert_does_not_reject(&mut self, promise_reg: u8) {
        self.emit_raw(Opcode::AssertDoesNotReject.as_u8(), promise_reg, 0, 0);
    }

    /// assert_fail - always fail
    pub fn emit_assert_fail(&mut self) {
        self.emit_raw(Opcode::AssertFail.as_u8(), 0, 0, 0);
    }
}
